pipeline:
  identifier: Build_Ashish1981_dbb_pipeline_1713965605488
  name: Build dbb-pipeline
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: Ashish1981/dbb-pipeline
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    command: echo hello world
                  timeout: ""
                  type: Run
          platform:
            os: Linux
            arch: Arm64
          runtime:
            type: Docker
            spec: {}
        type: CI
